version: '2'
volumes:
  resin-data:
services:
  rtl-sdr:
    build: ./rtl-sdr
    privileged: true
    restart: always
  serial-input:
    privileged: true
    build: ./serial-input
    restart: always
  broadcast:
    build: ./broadcast
    depends_on:
      - serial-input
      - rtl-sdr
    restart: always
  wifi-connect:
    image: bh.cr/balenalabs/wifi-connect-armv7hf
    restart: always
    network_mode: host
    privileged: true
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - PORTAL_SSID=BCA-Wifi-Connect
      - PORTAL_PASSPHRASE=BCA_pass
      - ACTIVITY_TIMEOUT=300
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'