volumes:
  resin-data:
services:
  serial-input:
    privileged: true
    build: ./serial-input
    restart: always
  broadcast:
    build: ./broadcast
    depends_on:
      - serial-input
    restart: always
