version: '2'
volumes:
  resin-data:
services:
  rtl-sdr:
    build: ./rtl-sdr
    privileged: true
    restart: always
  serial-input:
    privileged: true
    build: ./serial-input
    restart: always
  network-input:
    build: ./network-input
    restart: always
    ports:
      - '6501:6501/udp'
  broadcast:
    build: ./broadcast
    depends_on:
      - network-input
      - serial-input
      - rtl-sdr
    restart: always
