volumes:
  resin-data:

services:
  serial-input:
    privileged: true
    build: ./serial-input
    environment:
      - IS_RAW_MODE_ENABLED=true
    restart: always

  broadcast:
    build: ./broadcast
    depends_on:
      - serial-input
    restart: always
