version: '2'
volumes:
  resin-data:
services:
  rtl-sdr:
    build: ./rtl-sdr
    privileged: true
    restart: always
  serial-input:
    privileged: true
    build: ./serial-input
    restart: always
  broadcast:
    build: ./broadcast
    depends_on:
      - serial-input
      - rtl-sdr
    restart: always