name: New Release

on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: write
  packages: read
  pull-requests: write
  id-token: write # This is required to use OIDC with AWS

jobs:

  create-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Fetch all branches
        run: git fetch --prune

      - name: Show current branch
        run: git branch
      # Step 3: Extract the current version and increment it
      - name: Extract and increment version
        id: increment-version
        run: |
          # Extract the current version from balena.yml
          CURRENT_VERSION=$(yq eval '.version' balena.yml)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Create GitHub Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Crée le tag et pousse vers GitHub
          git tag -a "v${{ env.current_version }}" -m "Release version ${{ env.current_version }}"
          git push origin "v${{ env.current_version }}"
